#!/bin/bash

$(grep -A 1 project coverage/clover.xml | grep metrics | sed -e "s/.* statements=\"/export statements=/" -e "s/\"  coveredstatements=\"/\ncovered=/" -e "s/\".*//")

PERCENT_FLOAT=$(echo "$covered $statements" | awk '{print $1/$2}')

PERCENT=$(echo "$PERCENT_FLOAT 100" | awk '{printf("%.00f", $1*$2)}')
THRESHOLD=80

if [[ $PERCENT -ge $THRESHOLD ]]; then
  echo "Test coverage passed"
  exit 0
else
  echo "Test coverage failed"
  exit 1
fi
